### ISSUE TITLE
I can'T USed ThiS Pls Fix My App depends on IT

### ISSUE THREAD

**Issue by vnphanquang** [hungtruong97/nodejs#2]

**Comment by vnphanquang** [comment]
Installed it, run with `pnpm bcg gen --name "XXX" --email "xxx@gmail.com"` but nothing happens, PLEASE FIX ASAP!

**Comment by vnphanquang** [comment]
This is garbage I can't believe people recommends this package

**Comment by vnphanquang** [comment]
That's it, I'm switching to another one. I'm DONE

**Comment by hungtruong97** [comment]
fixed you mean mf! @vnphanquang
